contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #viralmetagenome channel"
    url: https://nfcore.slack.com/channels/viralmetagenome
    about: Discussion about the nf-core/viralmetagenome pipeline
