name: ivar_variants_to_vcf
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-forge::python=3.9.12
  - conda-forge::pandas=2.2.3
  - conda-forge::scipy=1.7.3
  - conda-forge::biopython=1.85
